# Generated by Django 5.2.5 on 2025-08-19 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("link", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="link",
            old_name="name",
            new_name="title",
        ),
        migrations.AddField(
            model_name="link",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name="Links",
        ),
    ]
