# Generated by Django 5.2.5 on 2025-08-11 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resume",
            name="resume",
        ),
        migrations.AddField(
            model_name="resume",
            name="resume_uri",
            field=models.URLField(blank=True, default=""),
        ),
    ]
