# Generated by Django 5.2.5 on 2025-08-11 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0002_remove_resume_resume_resume_resume_uri"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resume",
            name="date",
            field=models.DateTimeField(),
        ),
    ]
