# Generated by Django 5.2.5 on 2025-08-19 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0003_project_tags"),
        ("tag", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Tag",
        ),
        migrations.AlterField(
            model_name="project",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="projects", to="tag.tag"
            ),
        ),
    ]
